import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Pokemon } from "@/lib/types";
import { fetchAllPokemon } from "@/lib/fetch";

const inter = Inter({ subsets: ["latin"] });

type HomeProps = {
  pokemon: Pokemon[];
};
export default function Home({ pokemon }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Poxedex</h1>
        {pokemon.map((p) => (
          <a href="" key={p.id}>
            <p>{p.name}</p>
          </a>
        ))}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const pokemon = await fetchAllPokemon();
  return {
    props: {
      pokemon,
    }, // will be passed to the page component as props
  };
}
