import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import { Pokemon } from "@/lib/types";
import { fetchAllPokemon } from "@/lib/fetch";
import { GetStaticProps } from "next";

const inter = Inter({ subsets: ["latin"] });

type HomeProps = {
  /** All 151 Pokemon as an Array. */
  pokemon: Pokemon[];
};
export default function Home({ pokemon }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Poxedex</h1>
        {pokemon.map((p) => (
          <Link href={`/${p.name}`} key={p.id}>
            <img src={`/pokemon/${p.name}.jpg`} alt="" />
            <p>{p.name}</p>
          </Link>
        ))}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const pokemon = await fetchAllPokemon();
  return {
    props: {
      pokemon,
    }, // will be passed to the page component as props
  };
};
